// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartGarden.Data;

#nullable disable

namespace SmartGarden.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260908104015_SeedInitialPlantsData")]
    partial class SeedInitialPlantsData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartGarden.Shared.Entities.Garden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Gardens");
                });

            modelBuilder.Entity("SmartGarden.Shared.Entities.PlantProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DaysToHarvest")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Species")
                        .HasColumnType("int");

                    b.Property<int>("WateringFrequencyDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlantProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DaysToHarvest = 80,
                            Description = "Wysoka odmiana, wymaga palikowania.",
                            Name = "Pomidor Malinowy",
                            Species = 0,
                            WateringFrequencyDays = 2
                        },
                        new
                        {
                            Id = 2,
                            DaysToHarvest = 45,
                            Description = "Odmiana wczesna, bardzo słodka.",
                            Name = "Truskawka",
                            Species = 1,
                            WateringFrequencyDays = 1
                        },
                        new
                        {
                            Id = 3,
                            DaysToHarvest = 30,
                            Description = "Aromatyczne zioło, idealne do sałatek.",
                            Name = "Bazylia",
                            Species = 3,
                            WateringFrequencyDays = 3
                        });
                });

            modelBuilder.Entity("SmartGarden.Shared.Entities.PlantedCrop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<DateTime?>("EstimatedHarvestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GardenId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHarvested")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastWateredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlantProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlantingDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("YieldWeight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("GardenId");

                    b.HasIndex("PlantProfileId");

                    b.ToTable("PlantedCrops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 5.0,
                            EstimatedHarvestDate = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GardenId = 1,
                            IsHarvested = false,
                            LastWateredDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlantProfileId = 1,
                            PlantingDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Area = 2.5,
                            EstimatedHarvestDate = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GardenId = 1,
                            IsHarvested = false,
                            LastWateredDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlantProfileId = 3,
                            PlantingDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SmartGarden.Shared.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.HasIndex("Latitude", "Longitude")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartGarden.Shared.Entities.Garden", b =>
                {
                    b.HasOne("SmartGarden.Shared.Entities.User", "User")
                        .WithMany("Gardens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartGarden.Shared.Entities.PlantedCrop", b =>
                {
                    b.HasOne("SmartGarden.Shared.Entities.Garden", "Garden")
                        .WithMany("PlantedCrops")
                        .HasForeignKey("GardenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartGarden.Shared.Entities.PlantProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("PlantProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Garden");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("SmartGarden.Shared.Entities.Garden", b =>
                {
                    b.Navigation("PlantedCrops");
                });

            modelBuilder.Entity("SmartGarden.Shared.Entities.User", b =>
                {
                    b.Navigation("Gardens");
                });
#pragma warning restore 612, 618
        }
    }
}
