<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>a8db2869-7461-4008-897a-5e29cc547410</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\Pictures\logmenu.jpg" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\Pictures\logmenu.jpg" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SmartGarden.Shared\SmartGarden.Shared.csproj" />
    <ProjectReference Include="..\SmartGarden.Client\SmartGarden.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Syncfusion.Blazor.Charts" Version="34.2.6" />
  </ItemGroup>

</Project>
